listen: 127.0.0.1:8080
server_public_url: http://127.0.0.1:8080
diagnostic_endpoints_enabled: false
oidc:
    client_id: ""
    client_secret: ""
    issuer_url: ""
    cookie_key: kiel4teof4Eoziheigiesh6ooquiepho
    scopes:
        - openid
        - email
        - profile
        - offline_access
    allowed_group: ""
